lab4: wip2.c
	gcc -std=c23 \
		-Wall -Wextra -Wpedantic \
		-Wconversion -Wshadow -Wstrict-prototypes -Wfloat-equal -fno-common \
		-g3 -Og \
		-fsanitize=address,undefined -fsanitize-address-use-after-scope -fno-omit-frame-pointer -fstack-protector-all \
		wip2.c -o lab4 -lm
	./lab4
